version: '2'
services:

  backend:
    build: .
    container_name: gis-api
    ports:
      - '5000:5000'
    depends_on:
      - frontend
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: gis-frontend
    ports:
      - '3000:3000'
    volumes:
     - ./frontend:/app

volumes:
  db_data:
  bundle:
